<?php

const NO_IMAGE_PLACEHOLDER_PATH = '/local/templates/.default/images/no-image-placeholder.png';
const HITS_LINK = '/catalog/?sf_1062_4868592=Y&sf_P1_MIN=1&sf_P1_MAX=4141&set_filter=Y';

const CATALOG_SKU_DETAIL_PICTURES_MAX_WIDTH = 716;
const CATALOG_SKU_DETAIL_PICTURES_MAX_HEIGHT = 716;

const MAIN_PROFILE_PERSONAL_COUPONS_PICTURES_MAX_WIDTH = 323;
const MAIN_PROFILE_PERSONAL_COUPONS_PICTURES_MAX_HEIGHT = 279;

const MAIN_PAGE_SLIDER_PICTURES_DESKTOP_MAX_WIDTH = 1170;
const MAIN_PAGE_SLIDER_PICTURES_DESKTOP_MAX_HEIGHT = 560;
const MAIN_PAGE_SLIDER_PICTURES_TABLET_MAX_WIDTH = 1170;
const MAIN_PAGE_SLIDER_PICTURES_TABLET_MAX_HEIGHT = 560;
const MAIN_PAGE_SLIDER_PICTURES_MOBILE_MAX_WIDTH = 718;
const MAIN_PAGE_SLIDER_PICTURES_MOBILE_MAX_HEIGHT = 480;
