#!/usr/bin/env php
<?php

define('NO_AGENT_CHECK', true);
define('NOT_CHECK_PERMISSIONS', true);
define("PERFMON_STOP", true);

define('DISPOSER_APP', true);

require_once __DIR__ . '/bootstrap/autoload.php';

$_SERVER['DOCUMENT_ROOT'] = QSOFT_APPLICATION_ROOT  . '/app/site';
require_once $_SERVER['DOCUMENT_ROOT'] . '/bitrix/modules/main/include/prolog_before.php';

require_once __DIR__ . '/bootstrap/disposer.php';

exit(\QSoft\Foundation\Disposer::run());
