<?
$aMenuLinks = Array(
	Array(
		"AmeБизнес", 
		"/info/ame-business/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"FAQ", 
		"/info/faq/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Новости", 
		"/info/news/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Акции", 
		"/info/discounts/", 
		Array(), 
		Array("IMAGE"=>"1", "ADDITIONAL_CLASS_TAG"=>"button--dark-red", "SVG"=>"/local/templates/.default/images/icons/sprite.svg#icon-discount"), 
		"" 
	)
);
?>