<?php
/**
 * Created by PhpStorm.
 * User: vyfvfv
 * Date: 04.07.15
 * Time: 0:18
 */

namespace QSoft\Database\Query;

use Illuminate\Database\ConnectionInterface;
use Illuminate\Database\Query\Grammars\Grammar;
use Illuminate\Database\Query\Grammars\MySqlGrammar;
use Illuminate\Database\Query\Processors\MySqlProcessor;
use Qsoft\Database\Connection;
use Illuminate\Database\Query\Processors\Processor;

class Builder extends \Illuminate\Database\Query\Builder {


    public function __construct(ConnectionInterface $connection,
                                Grammar $grammar,
                                Processor $processor)
    {
        parent::__construct($connection, $grammar, $processor); // TODO: Change the autogenerated stub
    }

}