<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search", 
	".default", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/cart/",
		"CACHE_TIME" => "86400",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#CODE#",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => IBLOCK_PRODUCT,
		"IBLOCK_TYPE" => "catalog",
		"LINE_ELEMENT_COUNT" => "3",
		"NO_WORD_LOGIC" => "Y",
		"OFFERS_LIMIT" => "0",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "5",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => "",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array(
			0 => "PET_TYPE",
			1 => "VIDEO",
			2 => "PRODUCT_DETAILS",
			3 => "ENERGY",
			4 => "CALCIUM",
			5 => "COMPLETENESS",
			6 => "TREAT",
			7 => "LINE",
			8 => "MATERIAL",
			9 => "APPOINTMENT",
			10 => "NONRETURNABLE_PRODUCT",
			11 => "PRODUCT_FEATURES",
			12 => "PROTEIN",
			13 => "FEEDING_RECOMMENDATIONS",
			14 => "COMPOSITION",
			15 => "ROW_ASH",
			16 => "CRUDE_FIBRE",
			17 => "PRHOSPHORUS",
			18 => "BREED",
			19 => "AGE",
			20 => "FEED_TASTE",
			21 => "SPECIAL_INDICATIONS",
			22 => "",
		),
		"RESTART" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "/catalog/#SECTION_CODE_PATH#/",
		"SHOW_PRICE_COUNT" => "1",
		"USE_LANGUAGE_GUESS" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_SEARCH_RESULT_ORDER" => "Y",
		"USE_TITLE_RANK" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "SORT",
			3 => "PREVIEW_TEXT",
			4 => "IBLOCK_ID",
			5 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "BONUSES_K1",
			2 => "BONUSES_K2",
			3 => "BONUSES_K3",
			4 => "DISCOUNT_LABEL",
			5 => "SIZE",
			6 => "PACKAGING",
			7 => "IS_BESTSELLER",
			8 => "COLOR",
			9 => "CML2_LINK",
			10 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "ARTICLE",
			1 => "BONUSES_K1",
			2 => "BONUSES_K2",
			3 => "BONUSES_K3",
			4 => "DISCOUNT_LABEL",
			5 => "SIZE",
			6 => "PACKAGING",
			7 => "IS_BESTSELLER",
			8 => "COLOR",
			9 => "CML2_LINK",
		),
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>